#ifndef VA_MENU_H
#define VA_MENU_H

#include <stdbool.h>
#include <stdint.h>

struct u8g2_struct;

enum va_menu_page_id {
    VA_MENU_PAGE_NONE = 0,
    VA_MENU_PAGE_MAIN,
    VA_MENU_PAGE_DISCONNECT_CONFIRM,
    VA_MENU_PAGE_SETTINGS,
    VA_MENU_PAGE_SETTINGS_MISC,
    VA_MENU_PAGE_SETTINGS_BLUETOOTH,
    VA_MENU_PAGE_SETTINGS_BLUETOOTH_BONDED,
    VA_MENU_PAGE_SETTINGS_BLUETOOTH_BONDED_0,
    VA_MENU_PAGE_SETTINGS_BLUETOOTH_BONDED_0_CONFIRM,
    VA_MENU_PAGE_SETTINGS_BLUETOOTH_BONDED_1,
    VA_MENU_PAGE_SETTINGS_BLUETOOTH_BONDED_1_CONFIRM,
    VA_MENU_PAGE_SETTINGS_BLUETOOTH_BONDED_2,
    VA_MENU_PAGE_SETTINGS_BLUETOOTH_BONDED_2_CONFIRM,
    VA_MENU_PAGE_SETTINGS_BLUETOOTH_BONDED_3,
    VA_MENU_PAGE_SETTINGS_BLUETOOTH_BONDED_3_CONFIRM,
    VA_MENU_PAGE_SETTINGS_AUDIO,
    VA_MENU_PAGE_SETTINGS_AUDIO_VOLUME,
    VA_MENU_PAGE_SETTINGS_AUDIO_VIS,
    VA_MENU_PAGE_SETTINGS_AUDIO_OUTPUT,
    VA_MENU_PAGE_INFORMATION,
    VA_MENU_PAGE_INFORMATION_SYSTEM,
    VA_MENU_PAGE_COUNT,
};

bool va_menu_is_active(void);
void va_menu_update(void);
void va_menu_draw(struct u8g2_struct *u8g2);

#endif
